theme: jekyll-theme-minimal
title: Help Ajith
description: A website to contact Ajith in case a lost item is found.
logo: https://em-content.zobj.net/thumbs/60/google/298/sos-button_1f198.png
show_downloads: false
